"""
BashExplain - A command-line tool to explain Bash commands, errors, and scripts
"""

import sys
import re
import argparse
from typing import Dict, List, Tuple, Optional


class CommandExplainer:
    """Explains individual Bash commands and their components"""
    
    COMMON_COMMANDS = {
        'ls': 'List directory contents',
        'cd': 'Change directory',
        'pwd': 'Print working directory',
        'mkdir': 'Make directory',
        'rmdir': 'Remove empty directory',
        'rm': 'Remove files or directories',
        'cp': 'Copy files or directories',
        'mv': 'Move or rename files',
        'cat': 'Concatenate and display file contents',
        'grep': 'Search for patterns in text',
        'find': 'Search for files in directory hierarchy',
        'chmod': 'Change file permissions',
        'chown': 'Change file owner and group',
        'sudo': 'Execute command as superuser',
        'apt': 'Package manager (Debian/Ubuntu)',
        'yum': 'Package manager (RedHat/CentOS)',
        'systemctl': 'Control systemd services',
        'ps': 'Report process status',
        'kill': 'Send signal to process',
        'top': 'Display running processes',
        'echo': 'Display text or variables',
        'export': 'Set environment variable',
        'source': 'Execute commands from file in current shell',
        'tar': 'Archive files',
        'gzip': 'Compress files',
        'gunzip': 'Decompress files',
        'wget': 'Download files from the web',
        'curl': 'Transfer data from or to a server',
        'ssh': 'Secure shell remote login',
        'scp': 'Secure copy files over SSH',
        'git': 'Version control system',
        'docker': 'Container platform',
        'pip': 'Python package installer',
        'npm': 'Node.js package manager',
        'touch': 'Create empty file or update timestamp',
        'head': 'Display first lines of file',
        'tail': 'Display last lines of file',
        'less': 'View file contents page by page',
        'more': 'View file contents page by page (simpler)',
        'diff': 'Compare files line by line',
        'sed': 'Stream editor for text transformation',
        'awk': 'Pattern scanning and text processing',
        'sort': 'Sort lines of text',
        'uniq': 'Remove duplicate lines',
        'wc': 'Word, line, and byte count',
        'man': 'Display manual pages',
        'which': 'Show full path of command',
        'whereis': 'Locate binary, source, and manual page',
        'alias': 'Create command shortcut',
        'history': 'Show command history',
        'df': 'Report file system disk space usage',
        'du': 'Estimate file space usage',
        'free': 'Display memory usage',
        'uname': 'Print system information',
        'hostname': 'Show or set system hostname',
        'ping': 'Test network connectivity',
        'netstat': 'Network statistics',
        'ifconfig': 'Configure network interface',
        'ip': 'Show/manipulate routing and network devices',
    }

    COMMON_FLAGS = {
        '-a': 'All (include hidden files)',
        '-l': 'Long format (detailed listing)',
        '-h': 'Human-readable (sizes in KB, MB, GB)',
        '-r': 'Recursive (include subdirectories)',
        '-f': 'Force (don\'t prompt for confirmation)',
        '-v': 'Verbose (show detailed output)',
        '-i': 'Interactive (prompt before action)',
        '-n': 'Numeric (use numbers instead of names)',
        '-p': 'Parent (create parent directories if needed)',
        '-R': 'Recursive (uppercase version)',
        '-d': 'Directory (operate on directory itself)',
        '-s': 'Silent or summarize',
        '-u': 'Update or user',
        '-g': 'Group',
        '-o': 'Output file',
        '-e': 'Expression or edit',
        '-w': 'Word match',
        '-c': 'Count',
        '-x': 'Exclude or execute',
        '-z': 'Compress',
        '-t': 'Time or timestamp',
        '-k': 'Kill or kilobytes',
        '-m': 'Modify or message',
        '-q': 'Quiet (suppress output)',
        '-y': 'Yes (assume yes to prompts)',
        '-b': 'Backup',
        '--help': 'Display help information',
        '--version': 'Display version information',
        '--force': 'Force operation (do not prompt for confirmation)',
        '--recursive': 'Operate recursively (same as -r)',
        '--no-preserve-root': 'Do not treat "/" as special for "rm -rf" (dangerous)',
        '--dry-run': 'Show what would be done without making changes',
        '--no-clobber': 'Do not overwrite existing files',
        '--verbose': 'Show detailed output (same as -v)',
        '--quiet': 'Suppress most output (same as -q)',
    }

    UNSAFE_PATTERNS = [
        (r'rm\s+-rf\s+/', 'DANGEROUS: This will delete files starting from root directory'),
        (r'rm\s+-rf\s+--no-preserve-root', 'EXTREMELY DANGEROUS: Overrides safety and can delete the entire filesystem'),
        (r'rm\s+-rf\s+\.', 'DANGEROUS: Deletes the current directory recursively'),
        (r'rm\s+-rf\s+\*', 'DANGEROUS: Deletes all files in the current directory'),
        (r'chmod\s+777', 'UNSAFE: Grants full permissions to everyone'),
        (r'curl\s+.*\|\s*bash', 'RISKY: Executing downloaded script without inspection'),
        (r'curl\s+-sSL\s+.*\|\s*sh', 'RISKY: Silent download-and-execute without inspection'),
        (r'wget\s+.*\|\s*sh', 'RISKY: Executing downloaded script without inspection'),
        (r'wget\s+-qO-.*\|\s*bash', 'RISKY: Silent download-and-execute without inspection'),
        (r'sudo\s+chmod', 'CAUTION: Changing permissions as superuser'),
        (r'sudo\s+rm', 'CAUTION: Deleting files as superuser'),
        (r':\(\)\{.*\};:', 'DANGEROUS: Fork bomb - will crash system'),
        (r'dd\s+if=.*of=/dev/(?:sd|nvme|mmcblk)\b', 'DANGEROUS: Writing raw data to a disk device'),
        (r'fdisk\s+/dev/(?:sd|nvme|mmcblk)', 'DANGEROUS: Partitioning can destroy existing data'),
        (r'mkfs\.?', 'DANGEROUS: Formatting disk - will erase all data'),
        (r'echo\s+.*>\s*/etc/passwd', 'DANGEROUS: Overwriting system password file'),
        (r'kill\s+-9\s+1\b', 'DANGEROUS: Killing init process may crash the system'),
        (r'iptables\s+-F', 'CAUTION: Flushing firewall rules may break connectivity'),
        (r'systemctl\s+stop\s+ssh', 'CAUTION: Stopping SSH may lock you out of remote servers'),
        (r'chown\s+-R\s+root:root\s+/', 'CAUTION: Recursively changing ownership of root can break permissions'),
        (r'>\s*/dev/(?:sd|nvme|mmcblk)', 'DANGEROUS: Redirecting output to a disk device can overwrite it'),
        (r'cat\s+/dev/zero\s*>\s*/dev/(?:sd|nvme|mmcblk)', 'DANGEROUS: Overwriting disk with zeros'),
        (r'nohup\s+.*&\s*$', 'CAUTION: Backgrounding processes without control may leave unmanaged jobs'),
    ]